### PR TITLE
Fix drag&drop

### PR DESCRIPTION
**Pull request by Atlante45**

### CODE REVIEW

**Comment by birarda** [comment]
I think we want a dialog that confirms you actually want to upload the file you just dropped before we kick it off.

**Comment by Atlante45** [comment]
I think that's redundant. You know what file you dropped.
And if you dropped a file by accident, you'll just cancel.

**Comment by birarda** [comment]
Where will you get to cancel? If it's the first time you're dragging a file and you're just presented with the set asset path dialog, won't that be confusing?

**Comment by Atlante45** [comment]
You can just click cancel.

**Comment by birarda** [comment]
The problem isn't the absence of a cancel button, it's that you won't know what process you just kicked off and why you might want to accept or cancel it.

**Comment by Atlante45** [comment]
The box is saying "Upload your asset to the specific folder...."

**Comment by birarda** [comment]
Oh, didn't realize the wording had changed. Let's just verify with Alan that the flow is right.

**Pull request merged**
